### ISSUE TITLE
Suggestions: Add the possibility of mounting substations and beacons

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [rimbas/mining-patch-planner#1]
I would really like to be able to use substations instead of poles. It would also not be superfluous to install beacons.

Regarding lighthouses, I want to draw attention to the fact that Krastorio 2 mods change the original mechanics of lighthouses so that more than one beacon cannot affect one car otherwise it will not be able to work

**Comment by rimbas** [comment]
Currently looking into how implement blueprint support. I think that will be the best way to support beacon placement.
I'll give another look into substations when Wube releases an update that fixes dealing with wire connections electric pole ghosts.

**Comment by rimbas** [comment]
Implemented through blueprint support #4
