### ISSUE TITLE
Error when opening old save file with MPP 1.6.21

### ISSUE THREAD

**Issue by Sv443** [rimbas/mining-patch-planner#13]
Every time I try to open my old editor mode save, I get the following error and it doesn't open the save:
```
The mod Mining Patch Planner (1.6.21) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event mining-patch-planner::on_configuration_changed
__mining-patch-planner__/configuration.lua:206: attempt to index field 'filtered_entities' (a nil value)
stack traceback:
	__mining-patch-planner__/configuration.lua:206: in function 'update_player_data'
	__mining-patch-planner__/migration.lua:44: in function <__mining-patch-planner__/migration.lua:33>
```
Factorio version: 2.0.14  
Affected save file: [LAB.zip](https://github.com/user-attachments/files/17637879/LAB.zip)  
Mod list: [mod-list.json](https://github.com/user-attachments/files/17637880/mod-list.json)

**Comment by rimbas** [comment]
Thanks for the report, released a version with a fix.

**Comment by Sv443** [comment]
> Thanks for the report, released a version with a fix.

Very nice, thanks!  
PS: your mod was a staple ever since I began playing with mods, so thanks for making it :)
