### ISSUE TITLE
Failed to load sprite

### ISSUE THREAD

**Issue by jerodg** [rimbas/mining-patch-planner#14]
Factorio 2.0.13 & 2.0.14

![image](https://github.com/user-attachments/assets/926a6b73-0e31-4f38-9433-7d176e313dfa)

**Comment by rimbas** [comment]
I suspect it's a corrupted .zip file, can you try redownloading it?

**Comment by jerodg** [comment]
I redownloaded it twice. Got the latest update today and everything seems to be working now.
