### ISSUE TITLE
Stick with stable 

### ISSUE THREAD

**Issue by mmo-onn** [rimbas/mining-patch-planner#17]
Thanks so much for all the hard work you put into the planner, love the mod! It’s been a blast to use, and I really appreciate the time and effort you’ve dedicated to it.

The latest version of the mod requires the experimental version of Factorio. While I understand the appeal of using new features, I wanted to ask if it might be possible to keep the main branch of the mod compatible with the stable version of the game.

Switching Factorio versions to match mod updates can be a bit of a hassle. Having the default version of the mod work with the stable release of Factorio makes life a lot easier for players and server managers.

Thanks again for all that you do.

Cheers,
Mmoonn

**Comment by rimbas** [comment]
Glad you like it.
I did not realise releases for experimental have their own issues. Will keep it in mind for the future.

**Comment by mmo-onn** [comment]
Thanks for getting back to me! You’re absolutely right that the issue stems from the server mod updater downloading the latest version of your mod. However, this seems to only be a problem with your mod because other developers ensure their mods remain compatible with the stable branch of Factorio.

If your mod followed that same convention, it would prevent this kind of version mismatch and eliminate the need for servers and players to juggle different Factorio versions just to keep things running smoothly.

One possible solution could be to create an experimental branch for the mod on the mod portal. That way, players who want to use the latest features with the experimental Factorio branch can do so, while those sticking to the stable version can still enjoy your mod without any issues.

Again, love the mod, thank you for maintaining it, I really appreciate it!

Best regards,
Mmoonn

**Comment by rimbas** [comment]
ChatGPT?
