### ISSUE TITLE
Add support for miners from pyanodons mods

### ISSUE THREAD

**Issue by skofisk** [rimbas/mining-patch-planner#2]
Pyanodons mods adds a lot of different miners, that go on different types of ore patches, would me nice if mpp supported this.

- Crystal Mine, that mines Borax and Quartz. From PyCoalProcessing and PyRawOres
- Collector, mines from Bioreserve patches in PyAlienLife
- Molybdenite Mine from PyFusionEnergy
- Antimony Drill and Rare Earth Mining Drill from PyAlternativeEnergy (unreleased, alpha on py-discord)
- Molybdenite Mine and Antimony drill requires drill heads as input (item)
- Prob. more I have forgotten

Modportal: https://mods.factorio.com/user/pyanodon
Source: https://github.com/pyanodon

**Comment by rimbas** [comment]
Update with Pyanodons compatibility [6d9624c](https://github.com/rimbas/mining-patch-planner/commit/6d9624cced85a0e800202e5655c518ecef1c4639) has been released.
The hardcoded layouts are provided as-is. It's more intended to be used with custom blueprint layouts.
