### ISSUE TITLE
Failed to load mod

### ISSUE THREAD

**Issue by purple-emily** [rimbas/mining-patch-planner#3]
Invalid Parameter.

Using the latest version of the mod (1.2.7) on Factorio version 1.160

![image](https://user-images.githubusercontent.com/93710772/175647534-7ce59dbe-3ad2-4b3d-83e7-b3b4556b329c.png)

Any help appreciated

**Comment by purple-emily** [comment]
I think the zip file was corrupted. I beleive I have fixed this by cloning the git repository and recreating the zip file.

**Comment by rimbas** [comment]
Could've gotten corrupted while downloading? Can't find anything obviously wrong with 1.2.7 .zip in the mod portal. I don't know if Factorio validates checksums of downloads but it migh even be a dying storage problem?

Also try updating to 1.2.8 in-game or from mod portal, I forgot to push the fix commit so this repo is still 1.2.7
