### ISSUE TITLE
[SUGGESTIONS] Support for the Space Exploration platform

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [rimbas/mining-patch-planner#6]
The Space Exploration mod allows you to mine ore on asteroid fields and belts. Ores are spawned on asteroids of different shapes, which is why it is often necessary to place artificial platforms for the placement of drills, an analogue of landfill for space. Is it possible to add support for this?

**Comment by Eldrinn-Elantey** [comment]
When I already created the ticket, I wondered what if there is support but it does not work with custom blueprints

**Comment by rimbas** [comment]
The hardcoded layouts already support placing scaffold or platform in space.

Custom blueprints need a several improvements as a whole.

**Comment by rimbas** [comment]
Blueprints now automatically place landfill or space scaffold with update 1.6.0.
