### ISSUE TITLE
Crash when trying to use mining planner with "Rail deconstruction planner" mod

### ISSUE THREAD

**Issue by malomaster** [rimbas/mining-patch-planner#7]
I got this error when tried to use mining patch planner:
```
Mod Rail Deconstruction Planner (1.0.0) got an error.
Error while running event rail-decon-planner::on_player_selected_area (ID 51)
Entity is not rail.
stack traceback:
	[C]: in function 'get_rail_segment_rails'
	__rail-decon-planner__/control.lua:142: in function 'get_rail_segments'
	__rail-decon-planner__/control.lua:243: in function 'mark_segments'
	__rail-decon-planner__/control.lua:333: in function <__rail-decon-planner__/control.lua:330>
```
I tried to mark an ore patch for mining, but somehow got an error in "Rail Deconstruction Planner". I think both mods used the same functions and maybe the same locals (function names or smth), so using one mod also tried to call a function from another mod or something like that.
I'll also duplicate this error to "Rail Deconstruction Planner" author.

**Comment by rimbas** [comment]
Closing because crash is not on my end. The other mod is not properly filtering the `on_player_selected_area` event. (I had the same bug at first).

**Comment by fgardt** [comment]
Yeah that was entirely on my end.

```lua
if not event.item == "my-tool" then return end
```

was not properly checking the tool while

```lua
if event.item ~= "my-tool" then return end
```

does check it correctly.
